# Generated by Django 4.2.5 on 2024-12-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_task_task_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
