# Generated by Django 4.2.5 on 2024-12-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_task_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_task',
            name='solution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='completed_solution_photos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='solution_photos/'),
        ),
    ]
