# Generated by Django 4.2.5 on 2024-12-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_completed_task_solution_photo_task_solution_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_task',
            name='solution_photo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='solution_photo',
        ),
    ]
