# Generated by Django 4.2.5 on 2024-12-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_completed_task_solution_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_task',
            name='solution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='completed_solution_photos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='solution_photos/'),
        ),
    ]
